# Site settings
title: Craig Kahle
email: ckahle33@gmail.com.com
url: https://ckahle33.github.io
description: "Welcome to the site of Craig Kahle!"
skills: "Front-End Developer"
meta_author: Kahle Craig

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4FB6F0 #80B3FF
  primary-rgb: "79,182,240" #"128,179,255"
  secondary: FAB456 #FD6E8A
  secondary-dark: 61EB5F #A2122F

# Footer settings
footer:
  copyright: Craig Kahle
  location: Austin
  social: everywhere
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/craigkahle
  - title: facebook
    url: 
  - title: stack-overflow
    url: http://stackoverflow.com/users/1679747/cpk
  - title: github
    url: http://github.com/ckahle33

# Postal address (add as many lines as necessary)
address:
  - line: Austin, TX 78745

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
